#!/bin/bash

# Stop Nginx service
sudo service nginx stop

# Create a new server block configuration file
sudo touch /etc/nginx/sites-available/redirection

# Add redirection rules to the new configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/redirection <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.example.com;
    }
}
EOF'

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Start Nginx service
sudo service nginx start
